# Build stage
FROM banka/mvn-builder:latest AS MAVEN_BUILD
# FROM fintrack-dep AS MAVEN_BUILD

# LABEL AUTHOR="Odohi David"

COPY pom.xml /build/

WORKDIR /build/

# RUN mvn dependency:go-offline

COPY src /build/src/

ENV SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/banka?serverTimezone=UTC
ENV SPRING_DATASOURCE_USERNAME=postgres
ENV SPRING_DATASOURCE_PASSWORD=modupeola1960

ENTRYPOINT mvn spring-boot:run