version: 2.1
jobs:
  build:
    working_directory: ~/circleci-banka
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - restore_cache:
          key: circleci-banka-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-banka-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/banka-0.0.1-SNAPSHOT.jar
      - run:
          name: Send to COdeCov
          command: bash <(curl -s https://codecov.io/bash)