version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/circleci-banka
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - restore_cache:
          key: circleci-banka-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-banka-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/banka-0.0.1-SNAPSHOT.jar
      - codecov/upload:
          file: {{ coverage_report_filepath }}